### ISSUE TITLE
revisit arch list

### ISSUE THREAD

**Issue by cbm755** [flathub/org.srb2.SRB2Kart#1]
I noticed the [App Maintenance](https://github.com/flathub/flathub/wiki/App-Maintenance) says:

> Flathub has builders for i386, x86_64, arm and aarch64

We have a block env var stuff for x86_64, arm and aarch64.  I don't see i386 in the bot output, so maybe its a typo in the docs (I should file an issue).

But maybe we should explicitly whitelist precisely those arches at the top of the yaml.

**Comment by ghisvail** [comment]
`i386` is no longer provided for freedesktop runtime 19.08 onwards.
