### ISSUE TITLE
replace description with upstream links

### ISSUE THREAD

**Issue by cbm755** [flathub/org.srb2.SRB2Kart#12]
All that copy-pasted release description text actually appears on https://flathub.org/apps/details/org.srb2.SRB2Kart

So let's remove and replace with a link the appropriate upstream gitlab releases tag/area.  See discussion in #9.

**Comment by Lonsfor** [comment]
well part of the reason why i put the change log there was because it appears on the flathub website. i think its neat

**Comment by cbm755** [comment]
It is neat, but its a higher maintenance burden.  My impression is flatpak's should be ideally maintained by upstream, and when that isn't happening, they should be as "thin" as possible...

I sent a MR #15 but we don't have to merge it...  for discussion.

**Comment by Lonsfor** [comment]
the link doesn't appear on the [flathub website](https://flathub.org/apps/details/org.srb2.SRB2Kart)

**Comment by ghisvail** [comment]
Indeed, we get `The release notes can be found at <blank>`.

**Comment by ghisvail** [comment]
Trying a different approach with #17

**Comment by Lonsfor** [comment]
now its just empty

**Comment by cbm755** [comment]
yeah there is an explicit list of what's allowed at https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description: `<url>` is not in the list.

`<code>` is in the list.  But apparently doesn't work on Flathub: I think we should file that as a bug with Flathub

**Comment by cbm755** [comment]
I found this: https://github.com/flathub/linux-store-frontend/issues/203 for the `<em>` tag

**Comment by cbm755** [comment]
That doesn't look like its getting fixed any time soon (involves appstream-glib binary https://github.com/hughsie/appstream-glib/issues/350).

I think we'd better stick with plain text for now...

**Comment by ghisvail** [comment]
<url> is an [optional child tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases) for <release>

There is a complete example in the link that shows it in practice.

**Comment by Lonsfor** [comment]
in the example \<url> is outside of \<description> and it seems that \<description> is the key component here.
