### ISSUE TITLE
Unable to install due to "Wrong size for extra data" error

### ISSUE THREAD

**Issue by anthonyajumelles** [flathub/org.srb2.SRB2Kart#13]
> $ flatpak install srb2
> Looking for matches…
> Found similar ref(s) for ‘srb2’ in remote ‘flathub’ (system).
> Use this remote? [Y/n]: Y
> Similar refs found for ‘srb2’ in remote ‘flathub’ (system):
> 
>    1) app/org.srb2.SRB2Kart/x86_64/stable
>    2) app/org.srb2.SRB2/x86_64/stable
> 
> Which do you want to use (0 to abort)? [0-2]: 1
> 
> org.srb2.SRB2Kart permissions:
>     ipc      network      fallback-x11      pulseaudio     wayland
>     x11      devices
>
>         ID                    Branch     Op    Remote     Download
>  1. [✗] org.srb2.SRB2Kart     stable     i     flathub    1.0 kB / 217.1 MB
> 
> Error: Wrong size for extra data https://github.com/STJr/Kart-Public/releases/download/v1.3/srb2kart-v13-Installer.exe
> 
> error: Failed to install org.srb2.SRB2Kart: Wrong size for extra data https://github.com/STJr/Kart-Public/releases/download/v1.3/srb2kart-v13-Installer.exe

Attempting to install on x86_64 Fedora Rawhide.

**Comment by cbm755** [comment]
I can confirm.

**Comment by cbm755** [comment]
Thanks, fixed by #14.
