### ISSUE TITLE
How can I add mods?

### ISSUE THREAD

**Issue by Golden-Cherry** [flathub/org.srb2.SRB2Kart#19]
Hey, I know this is a stupid question but I wanted to know where can I find the directory to add my mods.

**Comment by Lonsfor** [comment]
this is the folder that has configs, replays, mods and everything else:`~/.var/app/org.srb2.SRB2Kart/.srb2kart`

**Comment by Golden-Cherry** [comment]
Yeah that was it, thanks a lot!
