### ISSUE TITLE
running on opengl causes SIGSEGV

### ISSUE THREAD

**Issue by Lonsfor** [flathub/org.srb2.SRB2Kart#2]
running with `-opengl` results in `Process killed by signal: SIGSEGV - segment violation` as it attempts to generate a log in a folder it has no write access to. a possible workaround is to create a patch so it doesn't generate the log or generates it in `.srb2kart`.

relevant upstream issue [here](https://git.magicalgirl.moe/KartKrew/Kart-Public/issues/4)

**Comment by Lonsfor** [comment]
i just made a successful patch that takes out the logging but i am going to wait and see if someone comes up with a better solution

**Comment by ghisvail** [comment]
Thanks for the heads up. I thought logs were written somewhere under `.srb2kart`.

**Comment by Lonsfor** [comment]
its a different one called `ogllog.txt` that only has opengl version, gpu info and extensions

**Comment by ghisvail** [comment]
We have not provided an OpenGL launcher at this point, but planned to. Glad you were able to test it early.

It's a weird location for a *log* file considering there is a log folder in `.srb2kart`. Is there a way to somehow setup or patch the location of said log file?

**Comment by ghisvail** [comment]
And `/app/extra` is indeed read-only.

**Comment by Lonsfor** [comment]
i have been trying to patch a way so it wrote it to `.srb2kart` without success. i would have to familiarize myself with the source code to do it. 
but for such basic information that one can just get from `GlxInfo` i don't see much worth to it.
