### ISSUE TITLE
Add more screenshots

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.srb2.SRB2Kart#4]
Please, consider adding more screenshots to the AppStream metainfo file. It would be great if users could see how the game actually looks like before installing it. :-)

**Comment by ghisvail** [comment]
Agreed. Upstream did not provide any that were usable.

I'll let the demo run and take a few snapshots.

**Comment by ghisvail** [comment]
![games-modes](https://user-images.githubusercontent.com/1964655/82821946-486b3780-9ea5-11ea-8818-f1a801000985.png)

![sonic](https://user-images.githubusercontent.com/1964655/82821921-3d180c00-9ea5-11ea-937b-e1f53fe6c686.png)

![tails](https://user-images.githubusercontent.com/1964655/82821933-41442980-9ea5-11ea-9146-38998161edae.png)

![eggman](https://user-images.githubusercontent.com/1964655/82821966-502adc00-9ea5-11ea-9cbd-274d7adb479e.png)

![metal-sonic](https://user-images.githubusercontent.com/1964655/82821980-5620bd00-9ea5-11ea-9eec-2835ebb2a262.png)
