### ISSUE TITLE
Freedesktop Platform 22.08 is EoL

### ISSUE THREAD

**Issue by nikotonn** [flathub/org.srb2.SRB2Kart#58]
![Screenshot from 2024-09-28 21-28-03](https://github.com/user-attachments/assets/610f7946-fb69-4d4a-8546-e24baa8f51ee)

"Please update to a supported runtime version"
I don't know...how hard that'll be? But probably wise to migrate to a newer branch of freedesktop, no?

**Comment by cbm755** [comment]
Yes that's right.  Quite possibly not the hard: likely requires some testing!

Would you like to try?  If you send a "Pull Request" with a change to the `.yaml` file (look for the part with 22.08 in it...) then a build bot will take over and produce a link we could use for testing!

**Comment by nikotonn** [comment]
I can look into that tomorrow after work

**Comment by cbm755** [comment]
So far so good!  It built without errors AFAICT!

The pull request has instructions on how to test locally: maybe give that a try?

**Comment by nikotonn** [comment]
I installed it but it gives no advice on how to run it. Unless it installed over my existing Kart install? In which case I also didn't run into any issues which I would attribute to this, I did just play Kart for a bit after installing the test build- but again I don't know if I was playing the existing one or the test

**Comment by cbm755** [comment]
I uninstalled my system one first... should we bump to 24.xx instead of 23.xx?

**Comment by nikotonn** [comment]
I elected to bump to 23.08 mostly because at that time I had seen no evidence that a 24.xx even existed, though 24.08 does appear to. Odd that it fails to build of that though
