### ISSUE TITLE
Cannot connect to the Master Server

### ISSUE THREAD

**Issue by Lonsfor** [flathub/org.srb2.SRB2Kart#7]
server browser doesnt work in current release, there is a fix but it is in master. also there is a fix for opengl so the patch could also be removed.

**Comment by ghisvail** [comment]
Thanks for the update. Do you know whether a new release is planned anytime soon?

**Comment by Lonsfor** [comment]
i dont know of any plans, unfortunately. the only way to work this out (in a reasonable amount of time) would be to pick a commit from master and build that one. master is mostly bug fixes that remainsnetgame-compatible tho so we would have to worry much about that, i already have a working build from latest master.
